name := "main/scala/assignment_03"
version := "1.0"
scalaVersion := "2.12.14"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.1.2"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.1.2"